/**
 * Route Quest: Automated Route Validator (Checker)
 * * Description:
 * A deterministic verification engine that simulates the delivery routes 
 * generated by the solver to mathematically prove constraint adherence.
 * * Validation Rules Enforced:
 * 1. Edge Existence (Valid Connectivity)
 * 2. Strict Fuel Capacity (Vehicle Survivability)
 * 3. Hub-to-House Dependency (Package Pickup Before Delivery)
 * 4. Complete Graph Traversal (All orders fulfilled)
 */

#include <bits/stdc++.h>
#include <ext/pb_ds/assoc_container.hpp>
#include <ext/pb_ds/tree_policy.hpp>

#pragma GCC optimize("Ofast,unroll-loops")

#define int long long
#define all(v) v.begin(), v.end()
#define rall(v) v.rbegin(), v.rend()

using namespace std;
using namespace __gnu_pbds;

template<class T> using ordered_set = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;

// ==========================================
// GLOBAL STATE & NETWORK GRAPH
// ==========================================
int n, t, m, k, fuel_capacity;
vector<vector<int>> graph;
vector<int> hubs, houses, fuel_stations;

// Fast O(1) Lookups
vector<int> is_hub, is_house, is_fuel_station;
map<int, int> house_to_hub;

void reset() {
    graph.clear(); hubs.clear(); houses.clear(); fuel_stations.clear();
    graph.resize(t + 1, vector<int>(t + 1, 1e18));
    hubs.resize(n + 1); houses.resize(n + 1); fuel_stations.resize(k + 1);

    is_hub.assign(t + 1, 0);
    is_house.assign(t + 1, 0);
    is_fuel_station.assign(t + 1, 0);

    house_to_hub.clear();
}

// ==========================================
// ENVIRONMENT SETUP
// ==========================================
void input() {
    cin >> n >> t >> m >> k >> fuel_capacity;
    reset();

    for(int i = 0; i < n; i++) {
        cin >> hubs[i];
        is_hub[hubs[i]] = 1;
    }
    for(int i = 0; i < n; i++) {
        cin >> houses[i];
        is_house[houses[i]] = 1;
        house_to_hub[houses[i]] = hubs[i]; // Map dependency
    }
    for(int i = 0; i < k; i++) {
        cin >> fuel_stations[i];
        is_fuel_station[fuel_stations[i]] = 1;
    }

    for(int i = 0; i < m; i++) {
        int a, b, c;
        cin >> a >> b >> c;
        graph[a][b] = c;
        graph[b][a] = c;
    }
    for(int i = 0; i <= t; i++) {
        graph[i][i] = 0;
    }
}

// ==========================================
// VALIDATION ENGINE
// ==========================================
void solve(int test_case_id) {
    string op = "output/output_" + to_string(test_case_id) + ".txt";
    freopen(op.c_str(), "r", stdin);

    int path_length_meta;
    cin >> path_length_meta;

    int path_length;
    cin >> path_length;

    vector<int> generated_path(path_length);
    for(int i = 0; i < path_length; i++) {
        cin >> generated_path[i];
    }

    int curr = generated_path[0];
    int current_fuel = fuel_capacity;

    set<int> visited_hubs;
    set<int> unvisited_houses;
    for(int i = 0; i < n; i++) {
        unvisited_houses.insert(houses[i]);
    }

    int total_cost = 0;
    
    // Simulate the truck driving the exact path generated by the solver
    for(int i = 1; i < path_length; i++) {
        int next = generated_path[i];

        // 1. Hub Logic: Mark hub as visited to unlock dependent houses
        if(is_hub[curr]) {
            visited_hubs.insert(curr);
        }

        // 2. House Logic: If the house's hub was visited, the package is delivered
        if(is_house[curr]) {
            if(visited_hubs.find(house_to_hub[curr]) != visited_hubs.end()) {
                unvisited_houses.erase(curr);
            }
        }

        // 3. Validation: Edge Existence (Does this road actually exist?)
        if(graph[curr][next] == 1e18) {
            cout << "non edge" << "\n";
            return;
        }
        
        // 4. Validation: Fuel Constraint (Did the truck run out of gas?)
        if(graph[curr][next] > current_fuel) {
            cout << "not enough fuel" << "\n";
            return;
        }
        
        // Drive to next node
        total_cost += graph[curr][next];
        current_fuel -= graph[curr][next];
        curr = next;

        // 5. Refuel Logic
        if(is_fuel_station[next]) {
            current_fuel = fuel_capacity;
        }
    }

    // Final check for the last node in the sequence
    if(is_house[curr]) {
        if(visited_hubs.find(house_to_hub[curr]) != visited_hubs.end()) {
            unvisited_houses.erase(curr);
        }
    }

    cout << "\n";
    
    // 6. Validation: Completeness (Were all orders successfully delivered?)
    if(unvisited_houses.size()) {
        cout << "all houses not traversed" << "\n";
    } else {
        cout << "OK" << "\n";
        cout << total_cost << "\n";
    }
}

signed main() {
    // Optimize I/O operations
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);

    // Loop through all test cases and validate outputs
    for(int i = 0; i < 3; i++) {
        string s = "tc/input_" + to_string(i) + ".txt";
        freopen(s.c_str(), "r", stdin);
        
        input();
        solve(i);
    }

    return 0;
}
